package event

import (
	"context"
	"time"

	"github.com/harrydayexe/AirportCapacityCalculator/internal/airport"
)

// OperationType defines the type of operations a runway can handle.
type OperationType int

const (
	// Mixed operations: runway handles both takeoffs and landings
	Mixed OperationType = iota
	// TakeoffOnly: runway only handles departures
	TakeoffOnly
	// LandingOnly: runway only handles arrivals
	LandingOnly
)

// String returns the string representation of the operation type.
func (ot OperationType) String() string {
	switch ot {
	case Mixed:
		return "Mixed"
	case TakeoffOnly:
		return "TakeoffOnly"
	case LandingOnly:
		return "LandingOnly"
	default:
		return "Unknown"
	}
}

// Direction defines the direction a runway is being used.
type Direction int

const (
	// Forward: runway is being used in the primary direction (e.g., 09)
	Forward Direction = iota
	// Reverse: runway is being used in the reciprocal direction (e.g., 27)
	Reverse
)

// String returns the string representation of the direction.
func (d Direction) String() string {
	switch d {
	case Forward:
		return "Forward"
	case Reverse:
		return "Reverse"
	default:
		return "Unknown"
	}
}

// ActiveRunwayInfo contains information about an active runway in the current configuration.
type ActiveRunwayInfo struct {
	RunwayDesignation string          // Runway identifier (e.g., "09L")
	OperationType     OperationType   // Type of operations (Mixed, TakeoffOnly, LandingOnly)
	Direction         Direction       // Direction being used (Forward, Reverse)
	Runway            airport.Runway  // Full runway configuration
}

// ActiveRunwayConfigurationChangedEvent represents a change in the active runway configuration.
// This is the single source of truth for which runways are operationally active.
// Generated by the RunwayManager when runway availability or curfew status changes.
type ActiveRunwayConfigurationChangedEvent struct {
	activeRunways map[string]*ActiveRunwayInfo // Map of runway ID to active runway info
	timestamp     time.Time                     // When this configuration becomes active
}

// NewActiveRunwayConfigurationChangedEvent creates a new runway configuration change event.
func NewActiveRunwayConfigurationChangedEvent(activeRunways map[string]*ActiveRunwayInfo, timestamp time.Time) *ActiveRunwayConfigurationChangedEvent {
	return &ActiveRunwayConfigurationChangedEvent{
		activeRunways: activeRunways,
		timestamp:     timestamp,
	}
}

// Time returns the time when this event occurs.
func (e *ActiveRunwayConfigurationChangedEvent) Time() time.Time {
	return e.timestamp
}

// Type returns the event type.
func (e *ActiveRunwayConfigurationChangedEvent) Type() EventType {
	return ActiveRunwayConfigurationChangedType
}

// Apply applies the event to the world state by updating the active runway configuration.
// This becomes the single source of truth for which runways the engine should use
// for capacity calculations.
func (e *ActiveRunwayConfigurationChangedEvent) Apply(ctx context.Context, world WorldState) error {
	return world.SetActiveRunwayConfiguration(e.activeRunways)
}

// ActiveRunways returns the active runway configuration.
// Returns a copy to prevent external mutation.
func (e *ActiveRunwayConfigurationChangedEvent) ActiveRunways() map[string]*ActiveRunwayInfo {
	// Return a copy to prevent external mutation
	copy := make(map[string]*ActiveRunwayInfo, len(e.activeRunways))
	for k, v := range e.activeRunways {
		copy[k] = v
	}
	return copy
}
